repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: detect-private-key
      - id: detect-aws-credentials
  - repo: https://github.com/jumanjihouse/pre-commit-hooks
    rev: 2.1.5  # or specific git tag
    hooks:
      - id: shellcheck
  - repo: https://github.com/sirosen/check-jsonschema
    rev: 0.4.1
    hooks:
      - id: check-github-workflows
